export const DIVISION_FILTER_REQUEST = 'DIVISION_FILTER_REQUEST ' 
export const DIVISION_FILTER_SUCCESS = 'DIVISION_FILTER_SUCCESS'
export const DIVISION_FILTER_FAILED = 'DIVISION_FILTER_FAILED'
export const SET_SELECTED_DIVISION = 'SET_SELECTED_DIVISION'